### ISSUE TITLE
Ask queries cause stack trace

### ISSUE THREAD

**Issue by whikloj** [Smithsonian/trippi-sparql#20]
Sending an ASK Sparql query causes a stack trace to appear in the fedora.log.

Query and stack trace are here - https://gist.github.com/whikloj/22da229f108318c0ee698c65d7fd3580

@ajs6f thinks the issue is here - https://github.com/Smithsonian/trippi-sparql/blob/master/trippi-sparql/src/main/java/edu/si/trippi/impl/sparql/SparqlSessionFactory.java#L75

**Comment by ajs6f** [comment]
4:41:09 PM - ajs6f: whikloj: I think it is here https://github.com/Smithsonian/trippi-sparql/blob/master/trippi-sparql/src/main/java/edu/si/trippi/impl/sparql/SparqlSessionFactory.java#L75
4:41:22 PM - ajs6f: whikloj: And that is a bug/gap in trippi-sparql
4:41:37 PM - ajs6f: q -> sparqlService(queryEndpoint, q).execSelect()
4:41:51 PM - ajs6f: whikloj: That is where I mistakenly assume that you are doing a select.

**Comment by whikloj** [comment]
So really this means that based on the type of query you might need to use the sparqlService.execSelect() or sparqlService.execAsk() or even sparqlService.execDescribe().

Maybe this is more trouble than it is worth, perhaps it would be easier to just not allow ASK and DESCRIBE queries. This is really an edge case, especially in Fedora 3.

**Comment by ajs6f** [comment]
You're right about what the fix is, but no, I think it's worth doing. People will be running F3 repos for several more years to come. It's worth putting all the nails into this thing we can. You just can't kill Fedora 3 too dead. I will fix this.
 
P.S. `DESCRIBE` is extremely useful for shimming purposes. More on that to come soon.

**Comment by ajs6f** [comment]
Also `Query::getQueryType` means the logic really isn't very onerous.

**Comment by whikloj** [comment]
I know you'll finish this before I get out of the gate, but would I be on the right track to remove the `Function<Query, ResultSet>` and replace it with `Function<Query, QueryExecution>` in the SparqlSession constructor, then in the `SparqlSession::query()` function do your `Query::getQueryType` comparison?

After that I'm not clear on how to return boolean, I think a DESCRIBE returns triples so it could use the same ResultSetTupleIterator.

**Comment by ajs6f** [comment]
Sort of. Keep in mind that `DESCRIBE` produces triples, so it would fit neatly, not into `Function<Query, ResultSet> queryExecutor`, but instead into `Function<Query, Model> constructExecutor`. But otherwise, yes, I think you're on the right trail. `QueryExecution` is the tool to take up.

**Comment by ajs6f** [comment]
Are you going to look at this this morning? Otherwise I will.

**Comment by whikloj** [comment]
I am going to look at it, but lets be honest here I probably won't get it done today. So for the sake of your sanity, you should just do what you need to. I have plenty of projects to split my time between 😄

**Comment by whikloj** [comment]
But because the `org.trippi.impl.base.TriplestoreSession` interface requires that the `query` method returns a `TupleIterator` that means that you have to create a tuple for the boolean result of the ASK query.

**Comment by ajs6f** [comment]
That means we would need to understand what Mulgara is returning there, not because it would be such a great idea, but because it's probably what people would expect. Want to start turning up your logs to `TRACE`?

**Comment by whikloj** [comment]
You mean for a setup using the internal Mulgara and that does work with `ASK` queries right?

**Comment by ajs6f** [comment]
Right, right. At this point we're just trying to recreate the useful behavior, right?
So one way to "probe" this would be for you to run an `ASK` query and look at the serialized results. Presumably there is a single variable and a single row, and what is the name of the variable?

**Comment by whikloj** [comment]
I bumped it to `TRACE` but there doesn't seem to be any trace logging, but the DEBUG logging looks like:
```
DEBUG 2017-02-09 18:56:22.113 [http-bio-8080-exec-1] (RISearchServlet) doGet()
  type: tuples
  template: null
  lang:  sparql
  query: PREFIX fedora-rels-ext: <info:fedora/fedora-system:def/relations-external#>

ASK {
?object fedora-rels-ext:isMemberOfCollection <info:fedora/islandora:root> .
FILTER (sameTerm(?object, <info:fedora/islandora:audio_collection>))
}
  limit: 1000
  distinct: null
  format: CSV
  flush: null
  dumbTypes: null

```

**Comment by ajs6f** [comment]
Erm, that doesn't help much, does it?

What do you get (for an answer at the endpoint) when you actually run the query and ask for tuple results?

**Comment by whikloj** [comment]
```
 curl -i -XGET "http://localhost:8080/fedora/risearch?lang=sparql&query=PREFIX%20fedora-rels-ext%3A%20%3Cinfo%3Afedora%2Ffedora-system%3Adef%2Frelations-external%23%3E%20ASK%20%7B%20%3Fobject%20fedora-rels-ext%3AisMemberOfCollection%20%3Cinfo%3Afedora%2Fislandora%3Aroot%3E%20.%20FILTER%20%28sameTerm%28%3Fobject%2C%20%3Cinfo%3Afedora%2Fislandora%3Aaudio_collection%3E%29%29%7D"
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=336509B842CE287D118934AAEA664587; Path=/fedora/; HttpOnly
Content-Type: application/xml;charset=UTF-8
Content-Length: 283
Date: Thu, 09 Feb 2017 19:25:59 GMT

<?xml version="1.0" encoding="UTF-8"?>
<sparql xmlns="http://www.w3.org/2001/sw/DataAccess/rf1/result">
  <head>
    <variable name="k0"/>
  </head>
  <results>
    <result>
      <k0 datatype="http://www.w3.org/2001/XMLSchema#boolean">true</k0>
    </result>
  </results>
</sparql>
```

**Comment by ajs6f** [comment]
Awesome-- now we know what to do: we build a result set with one row of one variable, the variable to be named `k0` with type as shown above.

**Comment by ajs6f** [comment]
Okely-dokely! Can you test this: https://github.com/Smithsonian/trippi-sparql/pull/21 and see what you think?

**Comment by ajs6f** [comment]
If the new work satisfied you, would you please close this issue?

**Comment by whikloj** [comment]
<img src="https://media.giphy.com/media/3o6MbeYMGsCxL11v0s/giphy.gif" height="200px" alt="Satisfied" />

**Comment by ajs6f** [comment]
https://www.youtube.com/watch?v=lVhATSQHw9k
<img src="http://j.gifs.com/El2wLk.jpg"/>
