### ISSUE TITLE
New triples added to weird graph

### ISSUE THREAD

**Issue by whikloj** [Smithsonian/trippi-sparql#22]
Using a configuration like.
```
  <datastore id="sparqlTriplestore">
    <comment>Triplestore addressed by SPARQL-over-HTTP used by the Resource Index</comment>
    <param name="connectorClassName" value="edu.si.trippi.impl.sparql.SparqlConnector">
        <comment>The name of the Trippi Connector class used to communicate with the triplestore.</comment>
    </param>
    <param name="readOnly" value="false">
        <comment>Whether this connector is going to be read-only in operation.</comment>
    </param>
    <param name="graphName" value="#ri">
        <comment>The URI of the named graph in which triples will be managed.</comment>
    </param>
    <param name="uriBase" value="info:ca.umanitoba.fedora">
        <comment>The base that will be used to resolve a graph name that is a relative URI.</comment>
    </param>
    <param name="maxHttpConnections" value="10">
        <comment>The maximum number of clients in the HTTP client pool used for SPARQL Update requests.</comment>
    </param>
    <param name="initialTripleStorePoolSize" value="3">
        <comment>The initial number of sessions in the triplestore pool.</comment>
    </param>
    <param name="maxTripleStorePoolGrowth" value="-1">
        <comment>The maximum number of additional sessions to add to the triplestore pool. If specified as -1, no limit will be placed on pool growth.</comment>
    </param>
    <param name="spareTripleStorePool" value="1">
        <comment>The number of spare sessions to maintain in the triplestore pool.</comment>
    </param>
    <param name="updateEndpoint" value="http://localhost:8080/bigdata/namespace/kb/sparql">
        <comment>The URL of a SPARQL Update endpoint for the triplestore to be used with this connector.</comment>
    </param>
    <param name="queryEndpoint" value="http://localhost:8080/bigdata/namespace/kb/sparql">
        <comment>The URL of a SPARQL Query endpoint for the triplestore to be used with this connector. This endpoint will be used for non-CONSTRUCT queries.</comment>
    </param>
    <param name="constructEndpoint" value="http://localhost:8080/bigdata/namespace/kb/sparql">
        <comment>The URL of a SPARQL Query endpoint for the triplestore to be used with this connector. This endpoint will be used for CONSTRUCT queries.</comment>
    </param>
    <param name="autoFlushDormantSeconds" value="5">
      <comment>Seconds of buffer inactivity that will trigger an auto-flush. If this threshold is reached, flushing will occur in the background, during which time the buffer is still available for writing.</comment>
    </param>
    <param name="bufferSafeCapacity" value="10000">
        <comment>The maximum size the buffer can reach before being forcibly flushed. If this threshold is reached, flushing will occur in the foreground and the buffer will be locked for writing until it is finished. This should be larger than autoFlushBufferSize.</comment>
    </param>
    <param name="bufferFlushBatchSize" value="5000">
        <comment>The number of updates to send to the triplestore at a time. This should be the same size as, or smaller than autoFlushBufferSize.</comment>
    </param>
    <param name="autoFlushBufferSize" value="5000">
        <comment>The size at which the buffer should be auto-flushed. If this threshold is reached, flushing will occur in the background, during which time the buffer is still available for writing.</comment>
    </param>
  </datastore>
```

I noticed that if I search my new graph `<info:ca.umanitoba.fedora#ri>` I am only getting the triples I pushed in during migration.

So checking a new object created via the Islandora UI. 
```
SELECT ?g ?p ?o
WHERE { GRAPH ?g { <info:fedora/uofm:gallery111> ?p ?o } }
```

returns

| g | p | o |
| --- | --- | --- |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;http://islandora.ca/ontology/relsext#inheritXacmlFrom&gt; | &lt;info:fedora/uofm:archives&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#createdDate&gt; | 2017-02-15T16:45:07.268Z |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#hasModel&gt; | &lt;info:fedora/fedora-system:FedoraObject-3.0&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#hasModel&gt; | &lt;info:fedora/islandora:collectionCModel&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#label&gt; | Gallery One One One |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#ownerId&gt; | umvielfn |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/model#state&gt; | &lt;info:fedora/fedora-system:def/model#Active&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/relations-external#isMemberOfCollection&gt; | &lt;info:fedora/uofm:archives&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/COLLECTION_POLICY&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/DC&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/MODS&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/POLICY&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/RELS-EXT&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:gallery111/TN&gt; |
| &lt;file:///var/lib/tomcat/null#ri&gt; | &lt;info:fedora/fedora-system:def/view#lastModifiedDate&gt; | 2017-02-15T16:45:07.485Z |
| &lt;file:///var/lib/tomcat/null#ri&gt; | dc:title | Gallery One One One |
| &lt;file:///var/lib/tomcat/null#ri&gt; | dc:description | Gallery One One One was established in 1965 to serve the School of Art and the public. The Gallery now exists as the School of Art Gallery and has been relocated to the Art Research Technology Laboratory (ARTlab). |
| &lt;file:///var/lib/tomcat/null#ri&gt; | dc:format | nonprojected graphic |
| &lt;file:///var/lib/tomcat/null#ri&gt; | dc:identifier | uofm:gallery111 |

Not sure what to say about that graph?

**Comment by ajs6f** [comment]
Hm. What version of `trippi-sparql` are you using?

**Comment by whikloj** [comment]
😨  crap v0.4.5... I guess I better upgrade tout suite

**Comment by ajs6f** [comment]
Did we even release a 0.4.5? :) Indeed, the latest release is really toot sweet. Of course, if you want to use `ASK`, you will have to go to trunk for the moment, since Dan has not yet made another release since your fine ticket on that score, but I don't think that could be involved here..

**Comment by whikloj** [comment]
0.4.5 was a SNAPSHOT. But I'm guessing I updated the configuration but the actual JAR was not ready for a separated uriBase and graphName

**Comment by ajs6f** [comment]
Y'yeah, that sounds right. We can find the commit if you really want to, but I would try upgrading first.

**Comment by whikloj** [comment]
👍  I'm build trippi-1.0 now, then I figure out how to migrate those triples into the correct graph

**Comment by ajs6f** [comment]
Wait, have you checked to see that later versions don't evidence your problem (I would be really surprised if they did, but JIC)?

**Comment by whikloj** [comment]
Tested in dev environment with trippi-sparql-1.1-SNAPSHOT and it works correctly.

| g | p | o |
| --- | --- | --- |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/model#state&gt; | &lt;info:fedora/fedora-system:def/model#Active&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/relations-external#isMemberOfCollection&gt; | &lt;info:fedora/uofm:test_collection&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/COLLECTION_POLICY&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/DC&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/MODS&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/POLICY&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/RELS-EXT&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#disseminates&gt; | &lt;info:fedora/uofm:trippiTest/TN&gt; |
| &lt;info:ca.umanitoba.fedora#ri&gt; | &lt;info:fedora/fedora-system:def/view#lastModifiedDate&gt; | 2017-02-17T15:27:15.532Z |
| &lt;info:ca.umanitoba.fedora#ri&gt; | dc:title | Trippi Sparql Test |
| &lt;info:ca.umanitoba.fedora#ri&gt; | dc:format | nonprojected graphic |
| &lt;info:ca.umanitoba.fedora#ri&gt; | dc:identifier | uofm:trippiTest |

 I'll try with a trippi-sparql-1.0 build and go from there.

**Comment by whikloj** [comment]
Tested with trippi-sparql-1.0. This was all on me 😞 

Closing...not actually a problem... with the software 😄

**Comment by ajs6f** [comment]
WORD.
