### ISSUE TITLE
SELECT queries leave hanging connections if not explicitly closed by client

### ISSUE THREAD

**Issue by ajs6f** [Smithsonian/trippi-sparql#23]

**Comment by sprater** [comment]
When running select queries through the Fedora risearch "Find Tuples" interface, TCP connections to the backend triplestore are not released after the query results are delivered and parsed.  This results in a growing stack of http connections left indefinitely in CLOSE_WAIT state;  when the number of connections reaches the configured sparqlTriplestore/maxHttpConnections value, Fedora can no longer reach the triplestore, and throws a ConnectionPoolTimeoutException with every attempt to reach the triplestore server.  The only way to recover is to restart the Fedora server.

Steps to reproduce:
1.  Set the sparqlTriplestore/maxHttpConnections in fedora.fcfg to something low, such as 10 connections, and restart Fedora
2.  Go to the fedora/risearch interface, "Find Tuples" tab
3.  Run a SELECT query, such as `SELECT * where { ?s ?p ?o . } limit 100`
4.  On the Fedora host command line, run the command `netstat -ntp | grep `<triplestore ip>:<triplestore port>`.  This will show you open TCP client connections to your triplestore server.
5.  After several seconds, ESTABLISHED connections will change to CLOSE_WAIT state.
6.  Repeat steps 3 - 4.  You should see a new connection for each query, as well as all the old connections.
7.  After the number of connections displayed by netstat reaches the maxHttpConnections value, Fedora will begin to throw exceptions when trying to reach the triplestore for any other query (SELECT, CONSTRUCT, whatever).

**Comment by ajs6f** [comment]
@sprater Please try the branch linked above and let me know here if it corrects the problem. Thanks very much for the report!

**Comment by sprater** [comment]
@ajs6f :  your fix did the trick!  When I run multiple SELECT queries now, connections are properly closed after the query, and no connections stack up.

**Comment by ajs6f** [comment]
Rad-tacular! We'll move this along to a release and keep you updated. In the meantime, are you still blocked on this or can you move ahead with the branch just for now? (Especially since the API obviously hasn't changed (and won't change in the release))?

**Comment by sprater** [comment]
I can use the jar I compiled from the branch for now, and replace it when the next version is released.  Thanks for your quick work on this!

**Comment by ajs6f** [comment]
Thanks for an excellent full bug report. That made it easy!

**Comment by ajs6f** [comment]
Oops-- I'll leave this open until the release is actually made.

**Comment by sprater** [comment]
Hi @ajs6f :  any chance on getting these fixes into a release soon?

**Comment by ajs6f** [comment]
Oh, goodness! @sprater I apologize profusely-- there was a release in October (1.2)! Did you not hear about it? That probably means I forgot to announce it! Oh, boy.

**Comment by sprater** [comment]
Ah, thanks! I see the new version at Maven Central.  I'll grab that.  You may want to update the wiki page, too:  https://confluence.si.edu/display/RISSC/Trippi-SPARQL

I think we can close this ticket, no?

**Comment by ajs6f** [comment]
Oh, I don't know. It's been open for so long, seems like a shame to close it now. Well, maybe it's better this way. :sigh: Goodbye, #23. You were a good ticket.
