### ISSUE TITLE
UTF-8 issues with Tomcat and Blazegraph

### ISSUE THREAD

**Issue by whikloj** [Smithsonian/trippi-sparql#27]
I may have already found my answer, but before I jump the gun I thought I would ask.

I just tried to ingest some French materials and Blazegraph is getting incorrect handling of the accented characters. 

In Fedora
```
Déclaration de 1908 d'André Nault, Elzéar Lagimodière et Duncan McDougall concernant les événements de 1869-70, extrait, fo. 353-354
```

In Blazegraph

```
DÃ©claration de 1908 d'AndrÃ© Nault, ElzÃ©ar LagimodiÃ¨re et Duncan McDougall concernant les Ã©vÃ©nements de 1869-70, extrait, fo. 353-354
```

According to Blazegraph this could be due to [Tomcat's assumption](https://sourceforge.net/p/bigdata/discussion/676946/thread/ee662025/#7e2a) that unless otherwise specified the contents of a POST request is ISO-8859-1.

So my plan is to write a Filter to set the character encoding. 

But I wanted to check in case this has already been handled in trippi-sparql. Which would indicate another problem.

**Comment by ajs6f** [comment]
I haven't heard anything like this from any user... `trippi-sparql` doesn't make any explicity assumptions of its own about encodings, but never say never! :) I think you are on the right track, so please let me know if the correction at Tomcat doesn't work and we'll take a closer look at `trippi-sparql`.

Cf: https://wiki.apache.org/tomcat/FAQ/CharacterEncoding#Q8

and consider, if possible, setting an explicit encoding on requests. If you need to do that via Fedora's RI API, we can add that to `trippi-sparql`, no prob!

**Comment by whikloj** [comment]
Ok, using the setCharacterEncodingFilter in Tomcat 7 seems to have worked. 

I'm not sure if there is a way to force a character encoding from Fedora.

But now I am wondering if there is an easy way to "re-index" a set of objects from Fedora to our 3store?

**Comment by ajs6f** [comment]
@whikloj and I discuss the reindexing question at http://irclogs.islandora.ca/2017-07-25.html .

Short answer; the stock Fedora 3 rebuilder utility may or may not work for small sets of objects, but the [hot indexer](https://github.com/ajs6f/fcrepo3-rdf-extractor) does.

**Comment by ddavis** [comment]
I don't know if this fits your case but any update operation to an object in F3 will cause it to be reindexed.

**Comment by whikloj** [comment]
@ddavis thanks, but it seems that it doesn't update the entire object rather just the changed triple is updated. So I have a French title and French names (both mangled), updating the title (read: label) only seems to have that triple updated in the 3store.

I'll try pulling the triples using the hot indexer and formulate a larger Sparql update.

**Comment by ajs6f** [comment]
@whikloj That's kind of weird. Having gone through that (Fedora 3) code (a long time ago), I'm pretty sure that in most cases, it should completely delete and rewrite _all_ of the triples for that object for most updates... just out of curiosity, are those triples coming from DC, RELS-*, or somewhere else...?

**Comment by whikloj** [comment]
@ajs6f I should clarify that I updated the label via Islandora, it is possible that it is doing some weird update. The fields are generated from the MODS datastream, however I believe the label is the actual Fedora object label.
